repos:
  - repo: https://github.com/terraform-docs/terraform-docs
    rev: v0.16.0
    hooks:
      - id: terraform-docs-go
        name: Terraform documentation ./s3
        args: ["markdown", "table", "--output-file", "README.md", "./s3"]
      - id: terraform-docs-go
        name: Terraform documentation ./bitwarden
        args: ["markdown", "table", "--output-file", "README.md", "./bitwarden"]
      - id: terraform-docs-go
        name: Terraform documentation ./rds
        args: ["markdown", "table", "--output-file", "README.md", "./rds"]
      - id: terraform-docs-go
        name: Terraform documentation ./mongodb
        args: ["markdown", "table", "--output-file", "README.md", "./mongodb"]
      - id: terraform-docs-go
        name: Terraform documentation ./cloudns
        args: ["markdown", "table", "--output-file", "README.md", "./cloudns"]
      - id: terraform-docs-go
        name: Terraform documentation ./ssm
        args: ["markdown", "table", "--output-file", "README.md", "./ssm"]
      - id: terraform-docs-go
        name: Terraform documentation ./cloudamqp-instance
        args: ["markdown", "table", "--output-file", "README.md", "./cloudamqp-instance"]
      - id: terraform-docs-go
        name: Terraform documentation ./eks-irsa
        args: ["markdown", "table", "--output-file", "README.md", "./eks-irsa"]
      - id: terraform-docs-go
        name: Terraform documentation ./cluster-scaler
        args: ["markdown", "table", "--output-file", "README.md", "./cluster-scaler"]
      - id: terraform-docs-go
        name: Terraform documentation ./app-of-apps
        args: ["markdown", "table", "--output-file", "README.md", "./app-of-apps"]
      - id: terraform-docs-go
        name: Terraform documentation ./argo-cd
        args: ["markdown", "table", "--output-file", "README.md", "./argo-cd"]
      - id: terraform-docs-go
        name: Terraform documentation ./cloudamqp-config
        args: ["markdown", "table", "--output-file", "README.md", "./cloudamqp-config"]
      - id: terraform-docs-go
        name: Terraform documentation ./ssm-lookup
        args: ["markdown", "table", "--output-file", "README.md", "./ssm-lookup"]
      - id: terraform-docs-go
        name: Terraform documentation ./vpc
        args: ["markdown", "table", "--output-file", "README.md", "./vpc"]
      - id: terraform-docs-go
        name: Terraform documentation ./vpc-peering
        args: ["markdown", "table", "--output-file", "README.md", "./vpc-peering"]
      - id: terraform-docs-go
        name: Terraform documentation ./eks
        args: ["markdown", "table", "--output-file", "README.md", "./eks"]
      - id: terraform-docs-go
        name: Terraform documentation ./lb-controller
        args: ["markdown", "table", "--output-file", "README.md", "./lb-controller"]
      - id: terraform-docs-go
        name: Terraform documentation ./efs
        args: ["markdown", "table", "--output-file", "README.md", "./efs"]
      - id: terraform-docs-go
        name: Terraform documentation ./ses
        args: ["markdown", "table", "--output-file", "README.md", "./ses"]
      - id: terraform-docs-go
        name: Terraform documentation ./sns
        args: ["markdown", "table", "--output-file", "README.md", "./sns"]
      - id: terraform-docs-go
        name: Terraform documentation ./newrelic-monitoring-cluster
        args: ["markdown", "table", "--output-file", "README.md", "./newrelic-monitoring-cluster"]
      - id: terraform-docs-go
        name: Terraform documentation ./newrelic-monitoring-customer
        args: ["markdown", "table", "--output-file", "README.md", "./newrelic-monitoring-customer"]
      - id: terraform-docs-go
        name: Terraform documentation ./newrelic-monitoring-global
        args: ["markdown", "table", "--output-file", "README.md", "./newrelic-monitoring-global"]
      - id: terraform-docs-go
        name: Terraform documentation ./jumphost
        args: ["markdown", "table", "--output-file", "README.md", "./jumphost"]
      - id: terraform-docs-go
        name: Terraform documentation ./iam-access-key
        args: ["markdown", "table", "--output-file", "README.md", "./iam-access-key"]
      - id: terraform-docs-go
        name: Terraform documentation ./elasticsearch
        args: ["markdown", "table", "--output-file", "README.md", "./elasticsearch"]
      - id: terraform-docs-go
        name: Terraform documentation ./kms
        args: ["markdown", "table", "--output-file", "README.md", "./kms"]
      - id: terraform-docs-go
        name: Terraform documentation ./kms-replica
        args: ["markdown", "table", "--output-file", "README.md", "./kms-replica"]
      - id: terraform-docs-go
        name: Terraform documentation ./sqs
        args: ["markdown", "table", "--output-file", "README.md", "./sqs"]
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.81.0
    hooks:
      - id: terraform_fmt
        name: Terraform format
        args:
        - --args=-recursive
      - id: terraform_tflint
        name: Terraform lint
        args:
        - --args=--minimum-failure-severity=error
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.9.0
    hooks:
    - id: shellcheck
      args: ["--severity=error"]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: check-yaml
    - id: check-xml
    - id: check-json
    - id: detect-private-key
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.0.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: []